### ISSUE TITLE
Hetzner reliable ?

### ISSUE THREAD

**Issue by gedw99** [la-cc/hetzner-proxmox-ha#1]
How has it been on hetzner ?

heard they were a little rough but would be nice to hear how it’s been

**Comment by la-cc** [comment]
@gedw99 
I have known Hetzner for years and I have to say that there have never ever been any problems. 

What they can do is provide server exchange or hardware. 
With Hetzner Cloud, they have expanded their portfolio so that you can get the most important services you need in this area. every service runs with IPV6. 

You can link the cloud with the hardware servers, it's quite powerful what they have built. 

Of course, it depends on your use cases, no shoe fits all. 

The only point they missed was to offer managed Kubernetes :/
